4.9.0.0:
  server: 'v2.0-176'
  rpi_client: 'v2.0-175'
  linux_client: '1.2-26'
4.7.2.0:
  server: 'v2.0-176'
  rpi_client: 'v2.0-175'
  linux_client: '1.2-26'
4.7.1.0:
  server: 'v2.0-170'
  rpi_client: 'v2.0-169'
  linux_client: '1.2-23'
4.7.0.0:
  server: 'v2.0-170'
  rpi_client: 'v2.0-169'
  linux_client: '1.2-23'
4.5.2.0:
  server: 'v2.0-170'
  rpi_client: 'v2.0-169'
  linux_client: '1.2-23'
4.5.1.0:
  server: 'v2.0-168'
  rpi_client: 'v2.0-164'
  linux_client: '1.2-19'
4.5.0.0:
  server: 'v2.0-168'
  rpi_client: 'v2.0-164'
  linux_client: '1.2-19'
4.3.2.0:
  server: 'v2.0-163'
  rpi_client: 'v2.0-160'
  linux_client: '1.2-18'
4.3.1.0:
  server: 'v2.0-157'
  rpi_client: 'v2.0-155'
  linux_client: '1.2-16'
4.3.0.0:
  server: 'v2.0-157'
  rpi_client: 'v2.0-155'
  linux_client: '1.2-16'
4.1.2.0:
  server: 'v2.0-157'
  rpi_client: 'v2.0-155'
  linux_client: '1.2-16'
r_2021_11:
  server: 'v2.0-153'
  rpi_client: 'v2.0-152'
  linux_client: '1.2-15'
r_2021_08:
  server: 'v2.0-148'
  rpi_client: 'v2.0-147'
  linux_client: '1.2-15'
r_2021_05:
  server: 'v2.0-144'
  rpi_client: 'v2.0-142'
